#!/usr/bin/env zsh

function tt {
	local DOCUMENTPATH=~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/Ideas/Journals/$(date +%Y-%m-%d).md

	if [ ! -f $DOCUMENTPATH ]; then
		echo "# $(date +%Y-%m-%d)\n" >$DOCUMENTPATH
	fi

	vim -c 'normal Go' $DOCUMENTPATH
}
