#!/usr/bin/env zsh

alias update='clear; __updateCommands; __updateNPM; __updateApps; __updateDock; __updatesCleanup;'

function __updateCommands {
	brew update
	brew upgrade
}

function __updateApps {
	brew cu -qay --cleanup --no-brew-update --no-quarantine
	mas upgrade
	sudo softwareupdate -i -a
}

function __updateNPM {
	npm -g update
}

function __updateRuby {
	sudo gem update --system
	sudo gem update
	sudo gem cleanup
}

function __updatesCleanup {
	brew cleanup -s
}

function __updateDock {
	dockutil -r all \
		-a /System/Cryptexes/App/System/Applications/Safari.app \
		-a /Applications/Google\ Chrome.app \
		-a /Applications/Arc.app \
		-a /System/Applications/Mail.app \
		-a /System/Applications/Calendar.app \
		-a /Applications/Notion.app \
		-a /Applications/Things3.app \
		-a /Applications/Visual\ Studio\ Code.app \
		-a /Applications/iTerm.app \
		-a /Applications/Whatsapp.app \
		-a /Applications/Telegram.app \
		-a /Applications/Slack.app \
		-a /System/Applications/Podcasts.app \
		-a /Applications/YouTube\ Music.app \
		-a /System/Applications/System\ Settings.app \
		-a ~/Desktop \
		-a ~/Downloads
}
