#!/usr/bin/env zsh

alias kp="kill_port $1"
alias k3="kp 3000"
alias k4="kp 4000"

alias gs="git status"
alias gundo="git reset --soft HEAD~1"
alias lg="lazygit"

alias c="code ."
alias ls='exa'
alias fuckdstore='find . -name ".DS_Store" -type f -delete'
alias tmux="TERM=screen-256color-bce tmux"
alias tm="tmux attach"
alias y="yarn"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias bim="nvim -u NONE"
alias ",tk"="tmux kill-server"

# lead alias
alias list_alias="" # show an alias list
alias ",s"="fzfnpm #launch fzfnpm"

alias ",sa"='echo -e "Hisco <leader> aliases\n"; alias | grep -E "^,"'
