#!/usr/bin/env zsh

alias coredist="sh ~/scripts/inject-griddo-core.sh"
alias cxdist="sh ~/scripts/inject-griddo-cx.sh"
alias gcx="yarn clean; yarn export"
alias gu="yarn add @griddo/{core,ax,cx} -E"
