#!/usr/bin/env zsh

# Dev Shortcuts
alias c="code"
alias c.="code ."
alias .="code ."

# Node Shortcuts
# alias nr="clear; pnpm run"
# alias nd="clear; pnpm run dev"
# alias ns="clear; pnpm run start"
# alias ni="clear; pnpm install"
# alias nig="clear; npm install -g"
# alias nis="clear; pnpm install -S"
# alias nid="clear; pnpm install -D"
# alias npx="pnpx"
alias y="yarn"
alias yi="yarn install 2> >(grep -v warning 1>&2)"
alias ys="yarn start"
alias yd="yarn dev"
alias r="npm run "

# Now Shortcuts
alias now="vercel"
alias deploy="vercel --prod"
