#!/usr/bin/env zsh

# List all files colorized in long format, including dot files

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # macOS `ls`
	colorflag="-G"
fi

# List all files colorized in long format
alias ls="clear; ls ${colorflag}"
alias l="ls"
alias lsa="ls -A"
alias ll="ls -hl"
alias lla="ll -A"
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias h="cd ~"
alias -- -="cd -"

# Main folder Navigation
alias d="cd $HOME/Desktop"
alias p="cd $HOME/Developer"
alias dot="cd $HOME/.config/dotfiles"
