#!/usr/bin/env zsh

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
function emptytrash() {
	sudo rm -rfv /Volumes/*/.Trashes/* 2>/dev/null
	sudo rm -rfv $HOME/.Trash/* 2>/dev/null
	sudo rm -rfv $HOME/Library/Mobile\ Documents/com\~apple\~CloudDocs/.Trash/* 2>/dev/null
	sudo rm -rfv /private/var/log/asl/*.asl 2>/dev/null
	sqlite3 $HOME/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
}

# Show in df only things I care
alias df="df -P -kHl"

# mkdir -p made quicker
alias mkdirp="mkdir -p"

alias path='echo -e ${PATH//:/\\n}'

alias rmr='trash'
